beginning of additonal git call hardening.

diff --git a/charts/mkdocs-material/templates/configmap-entry.yaml b/charts/mkdocs-material/templates/configmap-entry.yaml
--- a/charts/mkdocs-material/templates/configmap-entry.yaml
+++ b/charts/mkdocs-material/templates/configmap-entry.yaml
@@ -10,6 +10,27 @@ data:
   git-pull.sh: |-
     #!/bin/sh
 
+    ######################################################
+    # Exit and print error and command for git operations.
+    # Also cleans out all git state for next call.
+    # Arguments:
+    #   git command
+    #   captured output
+    #   exit code
+    # Returns:
+    #   1
+    ######################################################
+    print_git_error_exit() {
+      echo "Git command failed: {$1}"
+      echo "Output was: {$2}"
+      echo "Exit code was: {$3}"
+      echo "Deleting all git state..."
+      rm -f "/docs/.dirty"
+      cd /git
+      rm -rf *
+      exit 1
+    }
+
     update-ca-certificates
 
     if [ -n $DOCS_GIT_CRED_FILE ]; then
@@ -25,14 +46,30 @@ data:
         echo "Clearing and cloning git repo..."
         dirty=1
         rm -rf *
-        git clone "$DOCS_GIT_URL" .
+        gitcloneoutput=`git clone "$DOCS_GIT_URL" .`
+        if [ "$?" -ne "0" ]; then
+          print_git_error_exit "git clone ${DOCS_GIT_URL}" "$gitcloneoutput" "$?"
+        fi
+    else
+        ## Verify that the repository reference has not changed.
+        ## TODO: parse the out of git remote get-url origin
+        ## ensure that it is conststent with DOCS_GIT_URL
+        # git url passed as: https://gitlab.imcite.net/imcite/imcite.git
+        # git remote get-url origin
+        # git@gitlab.imcite.net:imcite/imcite.git
+        # git@gitlab.imcite.net:docs/docs.pages.imcite.net.git
     fi
 
+    ## Remove all local changes and any untracked and ignored files
     git reset --hard
-    git clean -f
+    git clean -f -d -x
 
     if [ -n "$DOCS_GIT_BRANCH" ]; then
         gitcheckoutoutput=`git checkout "$DOCS_GIT_BRANCH" 2>&1`
+        if [ "$?" -ne "0" ]; then
+          print_git_error_exit "git checkout ${DOCS_GIT_BRANCH}" "$gitcheckoutoutput" "$?"
+        fi
+
         echo "$gitcheckoutoutput" | grep "Switch*" > /dev/null 2>&1
         if [ "$?" -eq "0" ]; then
             echo "Branch changed - docs should be updated."
@@ -41,12 +78,19 @@ data:
     fi
 
     gitfetchoutput=`git fetch --porcelain`
+    if [ "$?" -ne "0" ]; then
+        print_git_error_exit "git fetch --porcelain" "$gitfetchoutput" "$?"
+    fi
+
     if [ -n "$gitfetchoutput" ]; then
         echo "Changes were made on remote branch - docs should be updated."
         dirty=1
     fi
 
-    git pull
+    gitpulloutput=`git pull`
+    if [ "$?" -ne "0" ]; then
+        print_git_error_exit "git pull" "$gitpulloutput" "$?"
+    fi
 
     if [ "$dirty" -eq "1" ]; then
         touch "/docs/.dirty"
@@ -56,13 +100,19 @@ data:
         if [ -n "$DOCS_GIT_PATH" ]; then
             echo "Docs path is: ${DOCS_GIT_PATH}"
             cd "${DOCS_GIT_PATH}"
+            if [ "$?" -ne "0" ]; then
+                echo "Failed to find the specified diredtory: ${DOCS_GIT_PATH}"
+            fi
         fi
 
-        sed -i -r -e "s#^(site_url: )(.*)#\1${DOCS_SITE_URL}#" mkdocs.yml
-        found_url=`grep -c 'site_url:' mkdocs.yml`
-        if [ $found_url = 0 ]; then
-        echo "site_url: ${DOCS_SITE_URL}" | cat - mkdocs.yml > tmp.yml
-        mv tmp.yml mkdocs.yml
+        if [ -f mkdocs.yml ]; then
+            sed -i -r -e "s#^(site_url: )(.*)#\1${DOCS_SITE_URL}#" mkdocs.yml
+            found_url=`grep -c 'site_url:' mkdocs.yml`
+            if [ $found_url = 0 ]; then
+            echo "site_url: ${DOCS_SITE_URL}" | cat - mkdocs.yml > tmp.yml
+            mv tmp.yml mkdocs.yml
+        else
+            echo "Failed to find the mkdocs.yml file."
         fi
     fi
 
